import { z } from "zod";

/**
 * Ledger types shared by the API and the browser.
 *
 * Money is always an integer number of cents — see `money.ts`. Amounts arrive
 * from the client already converted, so the server never parses "12.34".
 */

// ---------------------------------------------------------------------------
// Currencies
// ---------------------------------------------------------------------------

/**
 * The currencies a book can use. Deliberately a closed list: v1 treats every
 * currency as having two decimal places, which is true for all of these.
 * (JPY has none and would need special handling — recorded as a known limit.)
 */
export const CURRENCIES = ["CNY", "USD", "EUR", "JPY", "HKD", "GBP"] as const;

export const currencySchema = z.enum(CURRENCIES);
export type Currency = z.infer<typeof currencySchema>;

export const TRANSACTION_KINDS = ["expense", "income"] as const;
export const transactionKindSchema = z.enum(TRANSACTION_KINDS);
export type TransactionKind = z.infer<typeof transactionKindSchema>;

// ---------------------------------------------------------------------------
// Money
// ---------------------------------------------------------------------------

/**
 * Ceiling for a single entry: 10 billion units, i.e. 1e12 cents.
 *
 * Two reasons it exists. It keeps every amount inside JavaScript's safe
 * integer range, so cents can travel as numbers without precision loss; and it
 * rejects the typo that would otherwise poison every total.
 */
export const MAX_AMOUNT_CENTS = 1_000_000_000_000;

export const amountCentsSchema = z
  .number()
  .int("金额必须是整数（分）")
  .min(0, "金额不能为负数")
  .max(MAX_AMOUNT_CENTS, "金额超出可记录的上限");

// ---------------------------------------------------------------------------
// Identifiers
// ---------------------------------------------------------------------------

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Written as a regex rather than a helper so the rule is visible and stable
 * across zod versions. Entry ids are UUID v7 produced by the browser — see the
 * offline design in PLAN 3.3.
 */
export const uuidSchema = z.string().regex(UUID_PATTERN, "标识格式不正确");

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

/** Name of the system category that collects entries saved without one. */
export const UNCATEGORISED_NAME = "暂无分类";

export const categorySchema = z.object({
  id: z.string(),
  name: z.string(),
  kind: transactionKindSchema,
  /** System categories are server-managed and hidden from the picker. */
  isSystem: z.boolean(),
  isArchived: z.boolean(),
  sortOrder: z.number(),
});
export type Category = z.infer<typeof categorySchema>;

export const paymentMethodSchema = z.object({
  id: z.string(),
  name: z.string(),
  isArchived: z.boolean(),
  sortOrder: z.number(),
});
export type PaymentMethod = z.infer<typeof paymentMethodSchema>;

export const tagSchema = z.object({
  id: z.string(),
  name: z.string(),
  color: z.string(),
});
export type Tag = z.infer<typeof tagSchema>;

export const ledgerMetaResponseSchema = z.object({
  book: z.object({ id: z.string(), name: z.string() }),
  categories: z.array(categorySchema),
  paymentMethods: z.array(paymentMethodSchema),
  tags: z.array(tagSchema),
});
export type LedgerMetaResponse = z.infer<typeof ledgerMetaResponseSchema>;

// ---------------------------------------------------------------------------
// Entries
// ---------------------------------------------------------------------------

/** A tag may only be attached so many times to one entry. */
export const MAX_TAGS_PER_TRANSACTION = 10;
/** The list view shows this many; the detail view shows them all. */
export const TAGS_SHOWN_IN_LIST = 5;

const LOCAL_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

export const createTransactionSchema = z.object({
  /** Generated by the client so the entry keeps one identity from the start. */
  id: uuidSchema,
  /** Retrying an upload with the same key must not create a second row. */
  idempotencyKey: uuidSchema,

  kind: transactionKindSchema,
  amountCents: amountCentsSchema,
  currency: currencySchema,

  /** Omitted or null files the entry under 暂无分类. */
  categoryId: uuidSchema.nullish(),
  paymentMethodId: uuidSchema.nullish(),

  /** Full instant, ISO 8601 with an offset. */
  occurredAt: z.string().min(20).max(40),
  /** The phone's calendar date — what every group and month query uses. */
  occurredLocalDate: z.string().regex(LOCAL_DATE_PATTERN, "日期格式应为 YYYY-MM-DD"),
  /** IANA zone the entry was recorded in. */
  occurredTz: z.string().min(1).max(64),

  note: z.string().trim().max(200, "备注最多 200 个字符").nullish(),
  tagIds: z.array(uuidSchema).max(MAX_TAGS_PER_TRANSACTION, "一笔账最多 10 个标签").default([]),
});
export type CreateTransactionInput = z.infer<typeof createTransactionSchema>;

export const updateTransactionSchema = z.object({
  kind: transactionKindSchema.optional(),
  amountCents: amountCentsSchema.optional(),
  currency: currencySchema.optional(),
  categoryId: uuidSchema.nullish(),
  paymentMethodId: uuidSchema.nullish(),
  occurredAt: z.string().min(20).max(40).optional(),
  occurredLocalDate: z.string().regex(LOCAL_DATE_PATTERN).optional(),
  occurredTz: z.string().min(1).max(64).optional(),
  note: z.string().trim().max(200).nullish(),
  tagIds: z.array(uuidSchema).max(MAX_TAGS_PER_TRANSACTION).optional(),
  /** Optimistic lock: the version the client last saw. */
  version: z.number().int().positive(),
});
export type UpdateTransactionInput = z.infer<typeof updateTransactionSchema>;

export const transactionSchema = z.object({
  id: z.string(),
  kind: transactionKindSchema,
  amountCents: z.number(),
  currency: z.string(),
  categoryId: z.string(),
  categoryName: z.string(),
  categoryIsSystem: z.boolean(),
  paymentMethodId: z.string().nullable(),
  paymentMethodName: z.string().nullable(),
  occurredAt: z.string(),
  occurredLocalDate: z.string(),
  occurredTz: z.string(),
  note: z.string().nullable(),
  tags: z.array(tagSchema),
  version: z.number(),
});
export type Transaction = z.infer<typeof transactionSchema>;

export const transactionListResponseSchema = z.object({
  items: z.array(transactionSchema),
  /** Pass back as `cursor` to fetch the next page; null means the end. */
  nextCursor: z.string().nullable(),
});
export type TransactionListResponse = z.infer<typeof transactionListResponseSchema>;

// ---------------------------------------------------------------------------
// Monthly summary
// ---------------------------------------------------------------------------

/**
 * One line per currency. v1 never converts between currencies, so totals are
 * reported separately — adding ¥ and $ together would be meaningless.
 */
export const currencySummarySchema = z.object({
  currency: z.string(),
  expenseCents: z.number(),
  incomeCents: z.number(),
  balanceCents: z.number(),
  expenseCount: z.number(),
  incomeCount: z.number(),
  /** `|expense| + |income|`, used to rank which currencies are shown first. */
  volumeCents: z.number(),
});
export type CurrencySummary = z.infer<typeof currencySummarySchema>;

export const summaryResponseSchema = z.object({
  month: z.string(),
  currencies: z.array(currencySummarySchema),
});
export type SummaryResponse = z.infer<typeof summaryResponseSchema>;
